services:

  wordpress:
    container_name: proto-mouse-attack
    image: mouse-attack:proto
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mouse-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proto.mousefighter.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

networks:
    mouse-traefik:
        external: true