services:

  mouse-attack-proto:
    container_name: proto-mouse-attack
    image: mouse-attack:proto
    build:
      context: .
      dockerfile: ./MouseFighterProto.Server/Dockerfile
    networks:
      - mouse-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proto.mousefighter.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.api_compress.compress=true"
      - "traefik.http.routers.api.middlewares=api_compress"

networks:
    mouse-traefik:
        external: true